### PR TITLE
jquery-ui datepicker: add i18n

### PR DESCRIPTION
**Pull request by tenzap**

### CODE REVIEW

**Comment by kingster** [comment]
Instead of adding so many library files can't this be instead managed using composer or something similar?

**Comment by tenzap** [comment]
These files simply contain the parameters to localize datepicker which is already included in jquery-ui. However jquery-ui hasn't been shippind a minified version of these any more for a few versions now. So I guess there is no other option.

**Comment by tenzap** [comment]
We could limit to only the locales available in kalkun

**Comment by tenzap** [comment]
any comment please?

**Comment by tenzap** [comment]
I removed them. So that's only 16 new files.

**Comment by kingster** [comment]
Looks good for now. We should pick up a separate task to move all libs to composer or something that can pull from gitrepos

**Review by kingster — APPROVED** [review]

**Pull request merged**
