### PR TITLE
load js files asynchronously

### PR DESCRIPTION
**Pull request by tenzap**
Fixes this js warning:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

@kingster Are you ok with this approach?

### CODE REVIEW

**Comment by kingster** [comment]
Instead maybe move jquery js loading to footer of the page, since all pages requires jquery. For view specific ones, that can also happen at the end and outside dynamic (ajax) area.

**Comment by tenzap** [comment]
I doubt that what you suggest will change anything for this here. The point here is to not wait until everything is loaded. If you put it at the end, this may not fix the issue. Would it?

**Comment by kingster** [comment]
I meant we move it to the bottom of the view/footer so that no script tag comes as response of a ajax calls, that way we solve the loading problem.

Secondly we move all scripts to defer/async so that they don't block the rendering.

By doing these we won't need to write custom loader function, and still continue using html script tag for js file loading without any problems

**Comment by tenzap** [comment]
I think it's better they stay in the file where they are used. Having to search constantly in the other files if there is any js dependency called is not straightforward. So I disagree with putting them back to the "html part"

**Review by kingster — DISMISSED** [review]

**Comment by tenzap** [comment]
Approval got lost by a merge to fix conflicts. Please approve again.

**Review by kingster — APPROVED** [review]

**Pull request merged**
