### PR TITLE
Update the licence to GPL v3.

### PR DESCRIPTION
**Pull request by kingster**
Given that Gammu is licensed with  [GPL-2.0](https://github.com/gammu/gammu/blob/master/COPYING), Kalkun can't be MIT (it has to be GPL-v2/v3) as it interfaces with Gammu Ref https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#MereAggregation.

### CODE REVIEW

**Comment by back2arie** [comment]
@kingster could you also update the license in composer.json?

https://github.com/kalkun-sms/Kalkun/blob/c96478d582750f199d3638294eadb18435384d04/composer.json#L5

**Comment by kingster** [comment]
@back2arie @tenzap Any other places where the licence needs to be updated?

**Comment by back2arie** [comment]
Looks good to me 👍

**Comment by tenzap** [comment]
This file doesn't have a license

https://github.com/kalkun-sms/Kalkun/blob/devel/application/helpers/kalkun_helper.php

As well as some files in plugins dir.

**Comment by back2arie** [comment]
@tenzap for kalkun_helper I think it contains multiple contributors, looks like we need to trace the original author for all functions.

For plugins, I think it's safer to separate the codebase from the Kalkun repo, wdyt @kingster @tenzap?

**Comment by tenzap** [comment]
Very good idea to separate plugins and maybe put each in its separate repo.

If there are contributions from me in kalkun_helper the new gpl3 or later is ok for me.

**Comment by tenzap** [comment]
@kingster, @back2arie kalkun_helper has 4 contributors according to https://github.com/kalkun-sms/Kalkun/blob/devel/application/helpers/kalkun_helper.php

The 4th contributor is @pandigresik  with this contribution
https://github.com/kalkun-sms/Kalkun/commit/abe4609baa0895bc2ae68c5dc476de2ad0d9a906#diff-6e82283d3424e4e8b857c85f394c8e40e5991811a2570ca8014b37926ca79ead has

This is also the commit that did the change to MIT.

So?

**Pull request merged**
