### PR TITLE
Change XSS strategy

### PR DESCRIPTION
**Pull request by tenzap**
xss filtering should be done on output and not on input
See CI3 deprecation notice & #268  . The feature is already removed in CI 3.2 devel

One case where the old mode could actually have been a problem is when displaying an incoming SMS containing html code like <script>...</script>. The CI3 xss filtering that was used on input only, would have been of no use.

### CODE REVIEW

**Comment by tenzap** [comment]
I think this one is ready

**Comment by tenzap** [comment]
Any news please? I'm need this one for the upcoming changes... (asap)

**Review by kingster — APPROVED** [review]
Sorry for the delay, was offline last few days. These changes looks fine, only concern I had is that
1. This will cause those injections to be stored in database, is that expected behaviour 

2. we also need to handle sql injection on input given that we are removing the escaping part on input

**Comment by tenzap** [comment]
> This will cause those injections to be stored in database, is that expected behaviour
Yes, indeed, this is expected. There is no reason to alter the data entered by the user. Suppose the frontend is not in php/html but in another language, then there is no need to filter on output, but on html we have to escape. If I understood well it is view's job to filter the data for display

> we also need to handle sql injection on input given that we are removing the escaping part on input
What do you mean by sql injection? "hijacking" the sql queries by writing sql language in the input?

**Comment by kingster** [comment]
Sql injection is when someone uses specifically crafted input to change the query that is being sent to database and override the behavior /access.

https://portswigger.net/web-security/sql-injection

**Comment by tenzap** [comment]
Ok that's what I thought. Was that filtered out by the CI3 xss filter?

**Comment by tenzap** [comment]
If I understand well what is written in this paragraph CI already manages it? https://codeigniter.com/user_guide/database/queries.html#prepared-queries
What do you understand?

**Pull request merged**
