### PR TITLE
Don't use PREG_UNMATCHED_AS_NULL. Since it appeared in PHP 7.2

### PR DESCRIPTION
**Pull request by tenzap**
Fixes this error message:
Use of undefined constant PREG_UNMATCHED_AS_NULL - assumed 'PREG_UNMATCHED_AS_NULL'

### CODE REVIEW

**Comment by kingster** [comment]
Instead of completely removing this, can't we split the logic based on php version? That way when we remove old php version support we can cleanly remove old logic

**Comment by tenzap** [comment]
Too complex for no benefit. Moreover I prefer to keep compatibility with 5.6 at least for 0.8 so that those running old versions can still have a refreshed kalkun.

**Comment by tenzap** [comment]
Can you please "remove the outdated check in the protected branch settings of the repository settings. " so that waiting jobs can restart?

**Comment by tenzap** [comment]
What about this one here?

**Review by kingster — COMMENTED** [review]
Fine for now. Let's at least add a TODO so that its easily doable later.

**Comment by tenzap** [comment]
What about approval then? Should I wait for it or not?
Btw I initially wrote this plug-in. The use of the constant doesn't bring anything interesting.

**Review by kingster — APPROVED** [review]

**Comment by kingster** [comment]
Have approved for now. But as I mentioned we should add todo and switch back when we drop php 5.6 support

**Comment by tenzap** [comment]
But it is not available in 7.0 either... Neither 7.1...

**Comment by tenzap** [comment]
I still don't see the point sorry.

**Pull request merged**
