### PR TITLE
Change phpunit dependency to allow installation on php8

### PR DESCRIPTION
**Pull request by kingster**

### CODE REVIEW

**Comment by tenzap** [comment]
shouldn't this modify the composer.lock file too?

**Comment by kingster** [comment]
I didn't want to bump the lock file, as for me it was updating all versions since I am on php8. But looks like phpunittest are failing. Need to fix that.

**Comment by tenzap** [comment]
Should be in https://github.com/kalkun-sms/Kalkun/pull/384

**Comment by tenzap** [comment]
Is this still WIP?

**Comment by kingster** [comment]
Didn't get time to work on the fixes. I see that you had started working on #458 That should automatically take care of this!

**Comment by tenzap** [comment]
Then please close this if you think its done for you

**Pull request closed without merging**
