### PR TITLE
add color per signal level & connection status

### PR DESCRIPTION
**Pull request by hermesthecat**
Snipaste_2021-02-27_05-22-59

### CODE REVIEW

**Comment by tenzap** [comment]
How does this behave with other backends than gammu?

**Comment by tenzap** [comment]
@kingster what do you think about this? I agree that the current shading effect is not easy to read and could be improved as @hermesthecat suggests.

**Comment by kingster** [comment]
CSS looks fine to me, but the other changes needs to be localized, as in some places '%' is used after the number vs other places.

**Comment by tenzap** [comment]
@hermesthecat could you please pull latest devel fix the conflicts and push again?

Instead of `%'.$signal.'`, for localisation you should do this way:

```php
tr('{0}%', NULL, $signal);
```

And then add this line to all the language files (I can do this with a script if you prefer once this is merged)
```php
$lang['{0}%'] = '{0}%';
```

**Comment by tenzap** [comment]
@hermesthecat , the information is available now on screen but without eye-candy stuff. Please feel free to improve the design using CSS maybe? All required info is now provided in JSON format. A beautiful open source licensed battery status icon and network level icon would be great :)

**Pull request closed without merging**
