### PR TITLE
Move media/db to application/sql, drop cubrid support

### PR DESCRIPTION
**Pull request by tenzap**

### CODE REVIEW

**Review by kingster — COMMENTED** [review]
Any specific reason to drop the cubrid support?

**Comment by tenzap** [comment]
No SQL scripts to create db for cubrid in gammu?

**Comment by tenzap** [comment]
See: https://github.com/gammu/gammu/tree/master/docs/sql

**Comment by kingster** [comment]
Makes sense then.

**Review by kingster — APPROVED** [review]

**Pull request merged**
