### PR TITLE
Include vendor directory in dist.zip

### LINKED ISSUE #440: dist file produced by Github job has wrong vendor dir
In the dist.zip file produced by the build github action job the vendor dir is incorrect.

- system should be in `vendor/codeigniter/framework/system` and not in `vendor/codeigniter/framework/framework/system`
- new dependencies are missing
- autoload.php is also missing

@kingster, could you fix this please?

### PR DESCRIPTION
**Pull request by kingster**
Fixes #440

### CODE REVIEW

**Comment by tenzap** [comment]
Looks like it contains also the require-dev components. This makes a very big archive.

Could we only ship those that are in require?

The full debian packages will all dependencies don't take more that 6MB

**Comment by tenzap** [comment]
Just wondering... How would you do to get the dependencies for a system (typically for the demo on sourceforge) that runs PHP 7.1 when running a different php version?

**Comment by kingster** [comment]
For demo can't we run `composer install` and let composer pull in dependency based on php version?

**Comment by tenzap** [comment]
Anyway, looks like we have to build multiple dists, for a few selected versions of PHP

**Comment by tenzap** [comment]
fixed by #450  & #455

**Pull request closed without merging**
