### PR TITLE
set default CI_ENV to production

### PR DESCRIPTION
**Pull request by tenzap**
See: https://codeigniter.com/userguide3/general/environments.html

### CODE REVIEW

**Review by kingster — APPROVED** [review]

**Comment by tenzap** [comment]
I'm have some doubt on whether we should enable this by default. Maybe we should let the user do?

Setting this will make the error Dialog Show empty messages because errors like 500, 400, 404... Will not display anything, not even a word.

What do you think?

**Comment by kingster** [comment]
One thing that we can do, is that we add the option with default to 'Development' and then let the user change the configuration.

**Comment by tenzap** [comment]
Ok, and what do you think on either option? Which one to set now? Leave it to `development` and let the user doing when installed by advising him to do so?

(BTW, what about #443 & #439?)

**Comment by kingster** [comment]
Let's have 'Development' as default.

Responded on the other pr's

**Comment by tenzap** [comment]
thanks. done.

**Review by kingster — APPROVED** [review]

**Pull request merged**
